#!/bin/bash
set -euo pipefail

export DEBIAN_FRONTEND=noninteractive

apt-get update
apt-get install -y build-essential make

# We use snaps instead of workshop SDKs to better match CI workflows.
snap install go --channel=1.27/stable --classic
