#!/bin/bash
set -euo pipefail

# Add GOPATH to the system-wide profile.
# Needed because we install Go via snap rather than
# Workshop SDK, which normally handles this.
# If we don't do this, executables installed by
# "go install" won't be found in the PATH.
# We do this system-wide so it also applies to root shells (e.g. "sudo -i").
GOBIN_DIR="$(go env GOPATH)/bin"
echo "export PATH=\"$GOBIN_DIR:\$PATH\"" | sudo tee /etc/profile.d/go-path.sh > /dev/null
export PATH="$GOBIN_DIR:$PATH"

make deps
go install ./...
